- type: http
  id: external_traefik_gateway
  name: External Traefik Gateway
  hosts: ["http://${VCW_HOSTNAME}:80"]
  check.response.status: [404]
  schedule: '@every 30s'
  fields:
    scope: "${VCW_STACK_MODULEPREFIX}"
    type: external
    service: traefik
    area: gateway

- type: http
  id: internal_traefik_dashboard
  name: Internal Traefik Dashboard
  hosts: ["http://${VCW_HOSTNAME}:8080/dashboard"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "${VCW_STACK_MODULEPREFIX}"
    type: internal
    service: traefik
    area: dashboard
