#!/usr/bin/env bash

prefix="vcwc_traefik__$1"
prefix="vcwc_traefik__$1"

executionplane --silent docker container prune --force

if [[ "vcwc_traefik__metrics_monitor_heartbeat_data_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_traefik__metrics_monitor_heartbeat_data_volume"
		result=$(docker volume ls | grep "vcwc_traefik__metrics_monitor_heartbeat_data_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcwc_traefik__metrics_monitor_heartbeat_monitors_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_traefik__metrics_monitor_heartbeat_monitors_volume"
		result=$(docker volume ls | grep "vcwc_traefik__metrics_monitor_heartbeat_monitors_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcwc_traefik__traefik_traefik_config_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_traefik__traefik_traefik_config_volume"
		result=$(docker volume ls | grep "vcwc_traefik__traefik_traefik_config_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
