- type: http
  id: external_traefik_gateway
  name: External Traefik Gateway
  hosts: ["http://${VCW_STACK_HOSTNAME}:${MODECO_TRAEFIK_TRAEFIK_GATEWAY_PORT}"]
  check.response.status: [404]
  schedule: '@every 30s'
  fields:
    scope: "${VCW_STACK_MODULE_URLPREFIX}"
    type: external
    service: traefik
    area: gateway
# source
- type: http
  id: internal_traefik_dashboard
  name: Internal Traefik Dashboard
  hosts: ["http://${VCW_STACK_HOSTNAME}:${MODECO_TRAEFIK_TRAEFIK_DASHBOARD_PORT}/dashboard"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "${VCW_STACK_MODULE_URLPREFIX}"
    type: internal
    service: traefik
    area: dashboard
