---
version: '3'
services:

# START SERVICE vcwc/traefik
  traefik:
    image: ${VCW_REGISTRY}traefik:${VCW_TAG}
    environment: []
    command: []
    volumes: ['/var/run/docker.sock:/var/run/docker.sock', '${VCW_STACK_STACKPREFIX}_traefik_config_volume:/etc/traefik']
    ports: [${VCW_STACK_TRAEFIK_PORTS}]
    networks: [${VCW_STACK_NETWORKLOCAL}_overlay, ${VCW_STACK_NETWORKGLOBAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${VCW_STACK_TRAEFIK_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${VCW_STACK_TRAEFIK_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${VCW_STACK_TRAEFIK_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/traefik

networks: {${VCW_STACK_NETWORKLOCAL}_overlay: { external: true },${VCW_STACK_NETWORKGLOBAL}_overlay: { external: true }}
volumes: {${VCW_STACK_STACKPREFIX}_traefik_config_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
