#!/usr/bin/env bash

executionplane-info "EXECUTING CONTROLPLANE PAUSE"

# implementation can be overridden as required by the solution
# the default implementation executes on all components from the top component down
run pause --recurse $@
