#!/usr/bin/env bash
selectedNode="${@: -1}"

executionplane-info "EXECUTING CONTROLPLANE REMOVE"

.solution run stop . $selectedNode

.solution run shutdown . $selectedNode

.solution deploy down . $selectedNode
