#!/usr/bin/env bash

prefix="vcw_module_vcwc_traefik__$1"
prefix="vcw_module_vcwc_traefik__$1"

executionplane --silent docker container prune --force

if [[ "vcw_module_vcwc_traefik__metrics_monitor_heartbeat_config" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcw_module_vcwc_traefik__metrics_monitor_heartbeat_config"
		result=$(docker volume ls | grep "vcw_module_vcwc_traefik__metrics_monitor_heartbeat_config")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcw_module_vcwc_traefik__metrics_monitor_heartbeat_data_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcw_module_vcwc_traefik__metrics_monitor_heartbeat_data_volume"
		result=$(docker volume ls | grep "vcw_module_vcwc_traefik__metrics_monitor_heartbeat_data_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcw_module_vcwc_traefik__metrics_monitor_heartbeat_monitors_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcw_module_vcwc_traefik__metrics_monitor_heartbeat_monitors_volume"
		result=$(docker volume ls | grep "vcw_module_vcwc_traefik__metrics_monitor_heartbeat_monitors_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcw_module_vcwc_traefik__traefik_traefik_config_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcw_module_vcwc_traefik__traefik_traefik_config_volume"
		result=$(docker volume ls | grep "vcw_module_vcwc_traefik__traefik_traefik_config_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
