#!/usr/bin/env bash

executionplane --silent docker container prune --force
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "vcwc_traefik__metrics_monitor_heartbeat_config"
	result=$(docker volume ls | grep "vcwc_traefik__metrics_monitor_heartbeat_config")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "vcwc_traefik__metrics_monitor_heartbeat_data_volume"
	result=$(docker volume ls | grep "vcwc_traefik__metrics_monitor_heartbeat_data_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "vcwc_traefik__metrics_monitor_heartbeat_monitors_volume"
	result=$(docker volume ls | grep "vcwc_traefik__metrics_monitor_heartbeat_monitors_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "vcwc_traefik__traefik_traefik_config_volume"
	result=$(docker volume ls | grep "vcwc_traefik__traefik_traefik_config_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
